### ISSUE TITLE
Can't create courses. it says course Id already exists.

### ISSUE THREAD

**Issue by pareekbhagu** [Avinm/QuickSlots#1]
was trying the system for first time. so tried to create some entries. successfully added departments, batches and rooms but can't add courses .

**Comment by Avinm** [comment]
Is this a fresh install? Could you go see your courses table in the db? I just tested out on a fresh install and couldn't reproduce the issue

**Comment by swapnilbhade** [comment]
The project is good. but there is a problem while download timetable. I cannot see downloaded png image. its size is also 1kb and image viewer show me error that image is damaged

**Comment by Avinm** [comment]
Hi Swapnil,


This sounds like an issue with phantomjs. Phantomjs is an external component (a headless browser) which generates the timetable image. In the QuickSlots repo, there are two files in a folder called "phatomjs": phantomjs.exe for windows and phantomjs elf binary for linux. Depending on the platform you are running on, ensure that the corresponding file is present in this folder. Also, if you are running QuickSlots on linux ensure that the phantomjs binary is marked as executable (if not, run: chmod +x phantomjs ).


Hope this would be of help.


Regards,

Avin


________________________________
