### ISSUE TITLE
Timetable Download button not working

### ISSUE THREAD

**Issue by sohail0992** [Avinm/QuickSlots#10]
After allocating subjects to the timetable, In view timetable page when I click on download timetable button it took too much time but the timetable still not downloaded

**Comment by Avinm** [comment]
Hi,

Please refer https://github.com/Avinm/QuickSlots/issues/1#issuecomment-296399036 and see if it helps you.

Regards,
Avin
________________________________

**Comment by sohail0992** [comment]
Yeah thanks, it works but the image png image is empty only 0 bytes

`

**Comment by Avinm** [comment]
What platform are you on? Try downloading a statically linked phantomjs binary for your platform and replace the one shipped with quickslots with it.

Regards,
Avin
________________________________

**Comment by sohail0992** [comment]
I tried in windows and even replace the phantomjs file in the directory with the new one, but in windows, by clicking on the download button it takes too much time and not working

**Comment by Avinm** [comment]
This is most likely due to $_SERVER['SERVER_NAME'] returning ipv6 loopback ("::1") instead of plain old "127.0.0.1" these days. Should be fixed in https://github.com/Avinm/QuickSlots/commit/9576d04c8b0f559ad3f9b45735477b50eec2ff6f

**Comment by chandum68** [comment]
Hi sir
The file is downloaded but it is not open in any viewer....can I change image format in code

**Comment by Avinm** [comment]
Could you check the size of the image? Also what platform are you on? The supplied binaries are elf and PE for linux and windows respectively.

**Comment by chandum68** [comment]
Size 900kb

Running platform:windows7 32bit

**Comment by Avinm** [comment]
Could you share the image?

**Comment by chandum68** [comment]
Sir image not sharing sor

**Comment by Avinm** [comment]
Phantomjs docs say that it supports JPEG, you could try changing the extension here:
https://github.com/Avinm/QuickSlots/blob/5f77d9e6d84878c08ec4bf0069fbee558928fbe7/download.php#L11

Meanwhile I still believe that if the generated png image has a non zero size it is most likely a valid png

**Comment by chandum68** [comment]
https://drive.google.com/file/d/0BzbOt13bJbUtNlpabXZrS3NscjY3Y2VlR0RqaUFyWjlDeHM0/view?usp=drivesdk

**Comment by chandum68** [comment]
![iicm-b_dcme](https://user-images.githubusercontent.com/47805670/53254000-839e1a00-36e8-11e9-8a97-f3b7237fd16d.png)

**Comment by Avinm** [comment]
You were wrong, the file size is jus 988 bytes not 900kb, which is too small for a timetable's png image. If you open it with a text-editor/browser you can see the below error:
<img width="839" alt="screen shot 2019-02-22 at 9 27 31 pm" src="https://user-images.githubusercontent.com/11731803/53254164-d4ae0e00-36e8-11e9-9e22-4d614dd19962.png">

This says that the function mime_content_type used in downloads.php is not supported in your version of php. Please use a version of php which supports it: https://bugs.php.net/bug.php?id=71367

**Comment by chandum68** [comment]
Sorry sir,
IAM using wamp server..
It is suitable for this server

**Comment by chandum68** [comment]
Sir I have another problem....is there any option to merge 3 slots into single slot for Lab time tables

**Comment by Avinm** [comment]
You can mark 3 slots with the same course.

**Comment by chandum68** [comment]
For example we have 60 students
30 students go-to c program lab and remaining students goes to other departments lab

**Comment by Avinm** [comment]
Group them into 3 different batches and assign 3 different courses

**Comment by chandum68** [comment]
Kk sir thanQ...

Sir same faculty going to different departments ...so we can get faculty details from other department

**Comment by chandum68** [comment]
https://github.com/Avinm/QuickSlots/issues/10#issuecomment-466447158

Sir I need to download latest version wamp server for getting downloading image

**Comment by Avinm** [comment]
Refer http://webcache.googleusercontent.com/search?q=cache:FSsKP20Zh0oJ:forum.wampserver.com/read.php%3F2,51449,51525+&cd=2&hl=en&ct=clnk&gl=in&client=firefox-b-d

**Comment by chandum68** [comment]
https://github.com/Avinm/QuickSlots/issues/10#issuecomment-466464874
Please help me sir

**Comment by Avinm** [comment]
Sorry, but QuickSlots is meant to be set up by people with some basic understanding of programming. So I can't really continue helping you.

**Comment by chandum68** [comment]
Thanku sir... is there any web site for searching code

**Comment by chandum68** [comment]
![queery](https://user-images.githubusercontent.com/47805670/53280894-bb877a80-3745-11e9-82c5-303fad25554c.PNG)

i want to update php  it shows like this 
but how to open downloaded image opend

**Comment by Avinm** [comment]
Please raise an issue with wamp on how to enable `mime_content_type` function. If you are well versed in php you should already be able to understand http://webcache.googleusercontent.com/search?q=cache:FSsKP20Zh0oJ:forum.wampserver.com/read.php%3F2,51449,51525+&cd=2&hl=en&ct=clnk&gl=in&client=firefox-b-d
