### ISSUE TITLE
How To Select  the faculty name in course Creation page.

### ISSUE THREAD

**Issue by selvag** [Avinm/QuickSlots#11]
Hell
In course creation page there is one drop down list that shows the faculty for selecting to course.
am not able to select any faculty. I have have created 2 faculties. But the drop down shows only one admin faculty name, Which i have created in installation process. Here how can change the faculty. please help me. Because i need to select the name of particular faculty while creating the courses.

**Comment by Avinm** [comment]
Any admin can manage only faculty of his own department:
https://github.com/Avinm/QuickSlots/blob/5f77d9e6d84878c08ec4bf0069fbee558928fbe7/faculty.php#L90-L97

Create a head of department/dean in the required department to manage courses of faculties in that department.

**Comment by selvag** [comment]
The first user of the application is master user is correct. Which the user name created in the process of installing the application. After the process completed we have add any number of user with the type of dean or HOD. 
After that we will login with separate dean or HOD and create the faculties for that particular department is correct. 

And finally is there any options to allow break hour while creating the slots and is there any options to separate the subject as theory or practicals.

**Comment by selvag** [comment]
Hello Avin
 Thanks for your help. If i have any struggle i will contact you again..

**Comment by saravanansardhi** [comment]
I understandthe screen shot  disable slot means break.

 we are need to break duration 15 min or 30 min  class duration 1hrs

If it possible for duration change for break time

**Comment by Avinm** [comment]
Not as such, but as a hack you can define all slots as 30 minutes and assign one each for breaks and two each for classes.

Regards,
Avin
________________________________
