### ISSUE TITLE
how to add LDAP server and dn? 

### ISSUE THREAD

**Issue by SyedaNadia** [Avinm/QuickSlots#12]
Hi Avinm,
Database host: root
Database name: create_tables
Database User: admin
Database Password: 1234
LDAP Server: ?
LDAP DN: ?

please tell me, i don`t know some detail on the login, could you please help me...

thankx

**Comment by mcarpenterjr** [comment]
Do you use LDAP for directory access control?

**Comment by mcarpenterjr** [comment]
this might help you, https://github.com/Avinm/QuickSlots/issues/3

**Comment by Avinm** [comment]
Check out the issue Mark referenced - you can leave the ldap fields blank if you don't use it.

Regards,
Avin
________________________________

**Comment by saravanansardhi** [comment]
Hi Ji,
I have used to ur code

Could you tell me and share the query.

How to add the break and lunch time?

**Comment by Avinm** [comment]
Please search existing issues: https://github.com/Avinm/QuickSlots/issues/11

Regards,
Avin
________________________________

**Comment by saravanansardhi** [comment]
Sry ji

In this query not in there

**Comment by saravanansardhi** [comment]
Cold you help me ji

**Comment by Avinm** [comment]
Please search for "break" in the issue.

Regards,
Avin
________________________________
