### ISSUE TITLE
How to exclude ldap ?

### ISSUE THREAD

**Issue by subbirhosain27** [Avinm/QuickSlots#3]
i have manually excluded ldap option but another warning Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>) .
Can i install it on my localhost?

**Comment by Avinm** [comment]
You do not have to change anything manually to exclude ldap, just leave the ldap fields blank in the initial setup UI

**Comment by subbirhosain27** [comment]
thank you very much for your reply ..but alas! after giving database credentials it does nothing . in chrome console this message displays
 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.success (form.js:32)
    at n (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at w (jquery.min.js:4)
    at XMLHttpRequest.d (jquery.min.js:4)

**Comment by Avinm** [comment]
What webserver are you running on? Most likely your server is not configured to handle PHP

**Comment by subbirhosain27** [comment]
running wamp 
Apache Version: 2.4.17  
PHP Version: 5.6.16  -
Server Software: Apache/2.4.17 (Win64) PHP/5.6.16 - Port defined for Apache: 80
MySQL Version: 5.7.9 - Port defined for MySQL: 3306
also pdo extension enabled..

**Comment by Avinm** [comment]
That should be working then. Ping me on Gitter and maybe I can help quicker

**Comment by Avinm** [comment]
The hostname provided was incorrect. Closed
