### ISSUE TITLE
Username and password

### ISSUE THREAD

**Issue by toyorlee** [Avinm/QuickSlots#4]
I was unable to to sign in

I keep getting invalid username or password 

I'm using xampp

**Comment by toyorlee** [comment]
The first page was the setup.php 

I insert the hostmame db name 


I was unable to login from there because I keep getting invalid username or password

**Comment by Avinm** [comment]
Okay it seems, xampp comes with MariaDB. But QuickSlots is written for MySQL. Make sure you have an instance of MySQL running.

**Comment by toyorlee** [comment]
Xampp  support MySQL

**Comment by toyorlee** [comment]
And have imported the tables into the database

**Comment by Avinm** [comment]
From https://www.apachefriends.org/index.html: XAMPP is a completely free, easy to install Apache distribution containing MariaDB, PHP, and Perl. I do not see MySQL anywhere.

**Comment by toyorlee** [comment]
Really?

 Can you give me any one I can use?

**Comment by toyorlee** [comment]
What about wamp?

**Comment by Avinm** [comment]
Yes, you can use wamp. And you needn't import the tables. Setup.php does it on its own.

**Comment by toyorlee** [comment]
Thanks :)

**Comment by chandum68** [comment]
Hi sir, greeting the day sir,
I have problem with setup.php
How can I get login details.like database server, database name, username and password
IAM using wammpp server
