### ISSUE TITLE
Can't create first/dean or admin account.

### ISSUE THREAD

**Issue by DeeObah** [Avinm/QuickSlots#5]
Hi, I am trying to install but got stuck. After running setup and filling in required details, its not taking me anywhere. However the database was successfully created and populated with some tables. How do I go about creating the dean/admin account.

**Comment by Avinm** [comment]
Check your browser console for Javascript or Network errors. Setup.php would let you create the dean/admin account once the database tables are created.

**Comment by DeeObah** [comment]
Thanks, now working after granting permissions to "config.php"
