### ISSUE TITLE
cant loggin 

### ISSUE THREAD

**Issue by boniface193** [Avinm/QuickSlots#6]
sorry, am unable to log in, i tried using my localhost->Data base host, create_tables-> Database Name, root->database user. is not working

![timetable](https://user-images.githubusercontent.com/19141170/36908034-0424584c-1def-11e8-8103-a12b55e4102e.PNG)

**Comment by Avinm** [comment]
Are you still having this issue? You need to ensure that the database you provide has already been created and the user you provide should have the necessary permissions on it.

**Comment by Avinm** [comment]
Closing the issue, feel free to reopen if you still need help.
