### ISSUE TITLE
Unable to login the appliaction

### ISSUE THREAD

**Issue by rohitkappikere** [Avinm/QuickSlots#7]
Hi Avinm,
Unable to login the application as it as asking some detail on the login .. could you please help me out

**Comment by Avinm** [comment]
Sure, ping me on you can ping me on [gitter](https://gitter.im)

**Comment by rohitkappikere** [comment]
Could you please share the details for login into appliaction.

**Comment by Avinm** [comment]
You need to run the setup before you can log in. Please follow the installation instructions in the Readme

**Comment by rohitkappikere** [comment]
It is not updated.. Could you please call me on 9923031880 

Thanks & Regards, 

Rohit Kappikere 

99230341880 



Sent from Yahoo Mail on Android 
 
  On Tue, May 8, 2018 at 12:12 AM, Avin<notifications@github.com> wrote:   
You need to run the setup before you can log in. Please follow the installation instructions in the Readme

**Comment by Avinm** [comment]
For future reference, I've assumed basic understanding of databases, hosts, etc for running the setup. Please contact a sys admin if you are unsure what these are instead of opening issues.
