### ISSUE TITLE
Choose room dropdown not working

### ISSUE THREAD

**Issue by sohail0992** [Avinm/QuickSlots#9]
In the Allocate Timetable, after adding a subject to the timetable, when I click on choose room for a particular subject, the list of rooms could not appear. Although the database has a record of all rooms and the console is clear there are no errors.
![2018-08-12 2](https://user-images.githubusercontent.com/23142014/44002149-c29a2868-9e57-11e8-96f5-18b91c9f0a6f.png)
![2018-08-12 3](https://user-images.githubusercontent.com/23142014/44002150-c2eb2e8e-9e57-11e8-8df4-079d894fd19c.png)
![2018-08-12 4](https://user-images.githubusercontent.com/23142014/44002151-c34d17c0-9e57-11e8-96e3-1a6ccd4aed12.png)

**Comment by Avinm** [comment]
This happens when the room capacity that you provided (50 here) cannot hold the allowed batches of the course.
